import {
  Box,
  Center,
  HStack,
  Link,
  LinkBox,
  ListItem,
  Spacer,
  Stack,
  Text,
  UnorderedList,
} from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { MdOutlineEmail } from "react-icons/md";
import { BiLocationPlus, BiWorld } from "react-icons/bi";
import { AiFillGithub, AiOutlinePhone } from "react-icons/ai";
import { FiTwitter } from "react-icons/fi";
// import {Link} from "next/link"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box border={"1px solid gray"} mb="200px">
        <Box bg="#000080" textAlign={"center"}>
          <Text
            color="white"
            fontWeight={"500"}
            lineHeight="80px"
            letterSpacing="15px"
            fontSize={"5xl"}
          >
            BANJO TOLA
          </Text>
          <Text
            pb="20px"
            color="white"
            fontWeight={"400"}
            // lineHeight="20px"
            letterSpacing="4px"
            fontSize={"2xl"}
          >
            SOFTWARE DEVELOPER
          </Text>
        </Box>

        {/* <Box> */}
        <Stack w={"100%"} direction={{ base: "column", md: "row" }}>
          <Box
            // direction={{ base: "row", md: "row" }}
            w={{ base: "100%", md: "35%" }}
            pt="50px"
            bg={"#f7f7f7"}
          >
            <HStack mb="30px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="2xl"
                fontWeight="bold"
              >
                CONTACT
              </Text>
            </HStack>

            <HStack pb="6px" pr="20px">
              <Spacer />
              <Text color={"black"}>banjotola12@gmail.com</Text>{" "}
              <MdOutlineEmail />
            </HStack>
            <HStack pb="6px" pr="20px">
              <Spacer />
              <Text color={"black"}>+234-80-3094-7177</Text> <AiOutlinePhone />
            </HStack>
            <HStack pb="6px" pr="20px">
              <Spacer />
              <Text color={"black"}>Ikorodu, Lagos</Text> <BiLocationPlus />
            </HStack>
            <HStack pb="6px" pr="20px">
              <Spacer />
              <Link
                _hover={{ textDecoration: "none" }}
                cursor={"pointer"}
                as={Link}
                href="https://twitter.com/daddytoyosi"
              >
                <Text color={"#007bff"}>Twitter</Text>{" "}
              </Link>
              <FiTwitter />
            </HStack>
            <HStack  pb="6px" pr="20px">
              <Spacer />
              <Link
                _hover={{ textDecoration: "none" }}
                cursor={"pointer"}
                as={Link}
                href="https://github.com/Oluwaseun4244"
              >
                <Text color={"#007bff"}>Github</Text>{" "}
              </Link>
              <AiFillGithub />
            </HStack>
            <HStack mb="30px" pb="6px" pr="20px">
              <Spacer />
              <Link
                _hover={{ textDecoration: "none" }}
                cursor={"pointer"}
                as={Link}
                href="https://banjo-tola-folio.netlify.app/"
              >
                <Text color={"#007bff"}>Port Folio</Text>{" "}
              </Link>
              <BiWorld />
            </HStack>

            <HStack mb="25px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="2xl"
                fontWeight="bold"
              >
                EDUCATION
              </Text>
            </HStack>
            <HStack mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                fontWeight="bold"
              >
                Higher National Diploma
              </Text>
            </HStack>
            <HStack mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                // fontWeight="bold"
              >
                Computer Engineering
              </Text>
            </HStack>
            <HStack mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                // fontWeight="bold"
              >
                Yaba College of Technology
              </Text>
            </HStack>
            <HStack mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                // fontWeight="bold"
              >
                2015 - 2017
              </Text>
            </HStack>
            <HStack mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                // fontWeight="bold"
              >
                Yaba, Lagos
              </Text>
            </HStack>

            <HStack mt="30px" mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                fontWeight="bold"
              >
                National Diploma
              </Text>
            </HStack>
            <HStack mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                // fontWeight="bold"
              >
                Computer Engineering
              </Text>
            </HStack>
            <HStack mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                // fontWeight="bold"
              >
                Grace Polytechnic
              </Text>
            </HStack>
            <HStack mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                // fontWeight="bold"
              >
                2012 - 2014
              </Text>
            </HStack>
            <HStack mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                // fontWeight="bold"
              >
                Omu Ijebu
              </Text>
            </HStack>

            <HStack mt="40px" mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="2xl"
                fontWeight="bold"
              >
                SKILLS
              </Text>
            </HStack>
            <HStack mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                // fontWeight="bold"
              >
                React Js
              </Text>
            </HStack>
            <HStack mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                // fontWeight="bold"
              >
                Next Js
              </Text>
            </HStack>
            <HStack mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                // fontWeight="bold"
              >
                React Js
              </Text>
            </HStack>
            <HStack mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                // fontWeight="bold"
              >
                Chakra UI
              </Text>
            </HStack>
            <HStack mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                // fontWeight="bold"
              >
                Laravel
              </Text>
            </HStack>
            <HStack mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                // fontWeight="bold"
              >
                Bootstrap
              </Text>
            </HStack>
            <HStack mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                // fontWeight="bold"
              >
                MYSQL
              </Text>
            </HStack>

            <HStack mt="40px" mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}

                letterSpacing="2px"
                color={"black"}
                fontSize="2xl"
                fontWeight="bold"
              >
                FREECODECAMP
              </Text>
            </HStack>
            <HStack mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                // fontWeight="bold"
              >
                Javascript Algorithm and
              </Text>
            </HStack>
            <HStack mb="8px" w="100%">
              <Spacer />

              <Text
                pr="20px"
                // pl={{ base: "20px", md: "300px" }}
                letterSpacing="2px"
                color={"black"}
                fontSize="lg"
                // fontWeight="bold"
              >
                Data Structure
              </Text>
            </HStack>
          </Box>
          <Box w={{ base: "100%", md: "65%" }} pt="50px" bg="white">
            <Text
              mb="30px"
              pl="20px"
              letterSpacing="2px"
              color={"black"}
              fontSize="2xl"
              fontWeight="bold"
            >
              CAREER OBJECTIVE
            </Text>

            <Text pr="150px" pl="20px">
             I am an insightful and diligent IT Professional with with less than
              a year experience as a software developer, I am very comfortable
              using React.js, Chakra UI and Bootstrap styling. I have a strong
              desire to make a positive impact in any organization. I have
              excellent reputation for learning very fast, willing to learn,
              unlearn and relearn while delivering effective services.
            </Text>

            <Text
              mt="30px"
              mb="10px"
              pl="20px"
              letterSpacing="2px"
              color={"black"}
              fontSize="2xl"
              fontWeight="bold"
            >
              WORK EXPERIENCE
            </Text>

            <Text fontSize={"2xl"} fontWeight="500" pr="150px" pl="20px">
              Frontend developer
            </Text>
            <Text fontSize={"xl"} fontWeight="400" pr="150px" pl="20px">
              ITskillsCenter
            </Text>
            <Text
              mb="15px"
              fontSize={"xl"}
              fontWeight="400"
              pr="150px"
              pl="20px"
            >
              Oct 2021 - current
            </Text>

            <UnorderedList pr="150px" pl="40px">
              <ListItem>
                Assisted in converting an old website (https://eespace.com.ng)
                to new (https://staging.eespace.com.ng)
              </ListItem>
              <ListItem>
                Building both desktop and mobile friendly interface web apps
              </ListItem>
              <ListItem>
                Review codes and ensure quality of designs and implementations,
                and advocating clarity within the team
              </ListItem>
              <ListItem>Consumption of API’s</ListItem>
            </UnorderedList>

            <Text
              mt="50px"
              fontSize={"2xl"}
              fontWeight="500"
              pr="150px"
              pl="20px"
            >
              IT Support Officer
            </Text>
            <Text fontSize={"xl"} fontWeight="400" pr="150px" pl="20px">
              Lucky Fibres Limited
            </Text>
            <Text
              mb="15px"
              fontSize={"xl"}
              fontWeight="400"
              pr="150px"
              pl="20px"
            >
              Mar 2020 - Oct 2021 / Ikorodu, Lagos, Nigeria
            </Text>

            <UnorderedList pr="150px" pl="40px">
              <ListItem>Network, software and hardware maintenance</ListItem>
              <ListItem>
                Providing first-line support at every official computer users’
                desk
              </ListItem>
              <ListItem>
                Configuring and supporting company’s computers in LAN/WAN
                environment
              </ListItem>
              <ListItem>
                Providing technical support via phone, email and remotely
              </ListItem>
              <ListItem>
                Installation and configuration of Routers, Switches and cabling
              </ListItem>
              <ListItem>Network troubleshooting</ListItem>
            </UnorderedList>

            <Text
              mt="50px"
              fontSize={"2xl"}
              fontWeight="500"
              pr="150px"
              pl="20px"
            >
              IT Support Officer
            </Text>
            <Text fontSize={"xl"} fontWeight="400" pr="150px" pl="20px">
              Fidson Healthcare PLC
            </Text>
            <Text
              mb="15px"
              fontSize={"xl"}
              fontWeight="400"
              pr="150px"
              pl="20px"
            >
              June 2017 - Dec 2017 / 268, Ikorodu Road, Obanikoro
            </Text>

            <UnorderedList pr="150px" pl="40px">
              <ListItem>Network, software and hardware maintenance</ListItem>
              <ListItem>
                Configuring and supporting company’s computers in LAN/WAN
                environment
              </ListItem>
              <ListItem>
                Installation and configuration of Routers, Switches and cabling
              </ListItem>

              <ListItem>Network troubleshooting</ListItem>
            </UnorderedList>
          </Box>
        </Stack>
        {/* </Box> */}
      </Box>
    </div>
  );
}
